# Generated by Django 3.2.18 on 2023-06-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20230601_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_value',
            new_name='value',
        ),
    ]
